/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 27-Oct-2025 11:50:45
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型，二阶节
 * 节数     : 5
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\software\matlab2022a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.1254075319,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1254075319,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1185173616,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1185173616,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1161701009,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.789944649,   0.8593734503 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.991307735,   0.9915380478 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.975089669,   0.9753476977 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.615360022,    0.670709908 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.763955355,   0.7676597834 
  },
  {
                1,              0,              0 
  }
};
